In [1]:
import numpy

In [2]:
mylist = [1,2,3]

In [3]:
import numpy as np

In [4]:
np.array(mylist)

array([1, 2, 3])

In [6]:
np.random.rand(5) # Uniformly dist from 0 to 1

array([0.7395668 , 0.9925242 , 0.97060844, 0.84065013, 0.31849368])

In [7]:
np.random.randn(5) # standard normal dist/ Gaussian dist centred around zero.

array([ 0.33708544,  0.15105756,  0.20193128, -0.20515424,  0.3762949 ])

In [8]:
np.random.randint(1,101,10) #(low incl, highest excl, number of int required)

array([ 47,  54,  35,  20,  92,   3,  18,  93,  89, 100])

In [10]:
arr = np.arange(25)

In [11]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [12]:
ranarr = np.random.randint(0,50,10)

In [13]:
ranarr.min()

3

In [14]:
ranarr

array([ 5, 43, 22, 32, 40, 15, 17,  3, 42, 19])

In [15]:
ranarr.max()

43

In [16]:
ranarr.argmax()

1

In [17]:
ranarr.argmin()

7

In [18]:
arr.shape

(25,)

In [19]:
arr.dtype

dtype('int32')